name: Format & Linting

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Setup
        uses: denoland/setup-deno@004814556e37c54a2f6e31384c9e18e983317366
        with:
          deno-version: v1.x
          
      - name: Verify formatting
        run: deno fmt --check
        
# Uncomment this when src is properly linted
#      - name: Run linter
#        run: deno lint
        
# Uncomment this when testing is integrated!
#      - name: Run tests
#        run: deno test -A --unstable
